import React, { lazy } from "react";
import Head from 'next/head'
import Header from "../Header/Header";
import useChangeBoolHook from "../../hooks/useChangeBoolHook";
import dynamic from 'next/dynamic'
import { Box } from "@mui/material";

// import SearchBlock from "../SearchBlock/SearchBlock";

const SearchBlock = dynamic(() => import("../SearchBlock/SearchBlock"))

interface ILayoutProps {
    children: React.ReactNode
}

const Layout: React.FC<ILayoutProps> = ({children}) => {
    const {value, toggleValue, falseValue} = useChangeBoolHook()

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header toggleSearch={toggleValue} closeSearch={falseValue} show={value}/>
            <SearchBlock show={value}/>
            <Box className="_container overflow-hidden">
                {children}
            </Box>
        </>
    )
}
export default Layout;